// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseInfo.proto

package cn.cy.io.vo.protobuf;

/**
 * Proto文件生成的BaseInfo工具类
 * 
 */
public final class BaseInfoOuterClass {

    private BaseInfoOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface BaseInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:cn.cy.io.vo.BaseInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 type = 1;</code>
         */
        int getType();

        /**
         * <code>string desc = 2;</code>
         */
        String getDesc();

        /**
         * <code>string desc = 2;</code>
         */
        com.google.protobuf.ByteString
        getDescBytes();

        /**
         * <code>string requestId = 3;</code>
         */
        String getRequestId();

        /**
         * <code>string requestId = 3;</code>
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        boolean hasData();

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        com.google.protobuf.Any getData();

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        com.google.protobuf.AnyOrBuilder getDataOrBuilder();
    }

    /**
     * Protobuf type {@code cn.cy.io.vo.BaseInfo}
     */
    public static final class BaseInfo extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:cn.cy.io.vo.BaseInfo)
            BaseInfoOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use BaseInfo.newBuilder() to construct.
        private BaseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private BaseInfo() {
            desc_ = "";
            requestId_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private BaseInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            type_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            desc_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            requestId_ = s;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.Any.Builder subBuilder = null;
                            if (data_ != null) {
                                subBuilder = data_.toBuilder();
                            }
                            data_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(data_);
                                data_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return BaseInfoOuterClass.internal_static_cn_cy_io_vo_BaseInfo_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return BaseInfoOuterClass.internal_static_cn_cy_io_vo_BaseInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            BaseInfo.class, Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        private int type_;

        /**
         * <code>int32 type = 1;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int DESC_FIELD_NUMBER = 2;
        private volatile Object desc_;

        /**
         * <code>string desc = 2;</code>
         */
        public String getDesc() {
            Object ref = desc_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                desc_ = s;
                return s;
            }
        }

        /**
         * <code>string desc = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDescBytes() {
            Object ref = desc_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                desc_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REQUESTID_FIELD_NUMBER = 3;
        private volatile Object requestId_;

        /**
         * <code>string requestId = 3;</code>
         */
        public String getRequestId() {
            Object ref = requestId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                requestId_ = s;
                return s;
            }
        }

        /**
         * <code>string requestId = 3;</code>
         */
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            Object ref = requestId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATA_FIELD_NUMBER = 4;
        private com.google.protobuf.Any data_;

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        public boolean hasData() {
            return data_ != null;
        }

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        public com.google.protobuf.Any getData() {
            return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
        }

        /**
         * <code>.google.protobuf.Any data = 4;</code>
         */
        public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
            return getData();
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (type_ != 0) {
                output.writeInt32(1, type_);
            }
            if (!getDescBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desc_);
            }
            if (!getRequestIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, requestId_);
            }
            if (data_ != null) {
                output.writeMessage(4, getData());
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, type_);
            }
            if (!getDescBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desc_);
            }
            if (!getRequestIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, requestId_);
            }
            if (data_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(4, getData());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof BaseInfo)) {
                return super.equals(obj);
            }
            BaseInfo other = (BaseInfo) obj;

            if (getType()
                    != other.getType()) return false;
            if (!getDesc()
                    .equals(other.getDesc())) return false;
            if (!getRequestId()
                    .equals(other.getRequestId())) return false;
            if (hasData() != other.hasData()) return false;
            if (hasData()) {
                if (!getData()
                        .equals(other.getData())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + DESC_FIELD_NUMBER;
            hash = (53 * hash) + getDesc().hashCode();
            hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
            hash = (53 * hash) + getRequestId().hashCode();
            if (hasData()) {
                hash = (37 * hash) + DATA_FIELD_NUMBER;
                hash = (53 * hash) + getData().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static BaseInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BaseInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BaseInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BaseInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BaseInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static BaseInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static BaseInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BaseInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static BaseInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static BaseInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static BaseInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static BaseInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(BaseInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code cn.cy.io.vo.BaseInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:cn.cy.io.vo.BaseInfo)
                BaseInfoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return BaseInfoOuterClass.internal_static_cn_cy_io_vo_BaseInfo_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return BaseInfoOuterClass.internal_static_cn_cy_io_vo_BaseInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                BaseInfo.class, Builder.class);
            }

            // Construct using cn.cy.io.vo.BaseInfoOuterClass.BaseInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                type_ = 0;

                desc_ = "";

                requestId_ = "";

                if (dataBuilder_ == null) {
                    data_ = null;
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return BaseInfoOuterClass.internal_static_cn_cy_io_vo_BaseInfo_descriptor;
            }

            @Override
            public BaseInfo getDefaultInstanceForType() {
                return BaseInfo.getDefaultInstance();
            }

            @Override
            public BaseInfo build() {
                BaseInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public BaseInfo buildPartial() {
                BaseInfo result = new BaseInfo(this);
                result.type_ = type_;
                result.desc_ = desc_;
                result.requestId_ = requestId_;
                if (dataBuilder_ == null) {
                    result.data_ = data_;
                } else {
                    result.data_ = dataBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return super.clone();
            }

            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof BaseInfo) {
                    return mergeFrom((BaseInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(BaseInfo other) {
                if (other == BaseInfo.getDefaultInstance()) return this;
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (!other.getDesc().isEmpty()) {
                    desc_ = other.desc_;
                    onChanged();
                }
                if (!other.getRequestId().isEmpty()) {
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (other.hasData()) {
                    mergeData(other.getData());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                BaseInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (BaseInfo) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int type_;

            /**
             * <code>int32 type = 1;</code>
             */
            public int getType() {
                return type_;
            }

            /**
             * <code>int32 type = 1;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 type = 1;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private Object desc_ = "";

            /**
             * <code>string desc = 2;</code>
             */
            public String getDesc() {
                Object ref = desc_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    desc_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string desc = 2;</code>
             */
            public com.google.protobuf.ByteString
            getDescBytes() {
                Object ref = desc_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    desc_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string desc = 2;</code>
             */
            public Builder setDesc(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                desc_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string desc = 2;</code>
             */
            public Builder clearDesc() {

                desc_ = getDefaultInstance().getDesc();
                onChanged();
                return this;
            }

            /**
             * <code>string desc = 2;</code>
             */
            public Builder setDescBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                desc_ = value;
                onChanged();
                return this;
            }

            private Object requestId_ = "";

            /**
             * <code>string requestId = 3;</code>
             */
            public String getRequestId() {
                Object ref = requestId_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    requestId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string requestId = 3;</code>
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string requestId = 3;</code>
             */
            public Builder setRequestId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                requestId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string requestId = 3;</code>
             */
            public Builder clearRequestId() {

                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }

            /**
             * <code>string requestId = 3;</code>
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                requestId_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.Any data_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> dataBuilder_;

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public boolean hasData() {
                return dataBuilder_ != null || data_ != null;
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public com.google.protobuf.Any getData() {
                if (dataBuilder_ == null) {
                    return data_ == null ? com.google.protobuf.Any.getDefaultInstance() : data_;
                } else {
                    return dataBuilder_.getMessage();
                }
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public Builder setData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    data_ = value;
                    onChanged();
                } else {
                    dataBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public Builder setData(
                    com.google.protobuf.Any.Builder builderForValue) {
                if (dataBuilder_ == null) {
                    data_ = builderForValue.build();
                    onChanged();
                } else {
                    dataBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public Builder mergeData(com.google.protobuf.Any value) {
                if (dataBuilder_ == null) {
                    if (data_ != null) {
                        data_ =
                                com.google.protobuf.Any.newBuilder(data_).mergeFrom(value).buildPartial();
                    } else {
                        data_ = value;
                    }
                    onChanged();
                } else {
                    dataBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public Builder clearData() {
                if (dataBuilder_ == null) {
                    data_ = null;
                    onChanged();
                } else {
                    data_ = null;
                    dataBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public com.google.protobuf.Any.Builder getDataBuilder() {

                onChanged();
                return getDataFieldBuilder().getBuilder();
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            public com.google.protobuf.AnyOrBuilder getDataOrBuilder() {
                if (dataBuilder_ != null) {
                    return dataBuilder_.getMessageOrBuilder();
                } else {
                    return data_ == null ?
                            com.google.protobuf.Any.getDefaultInstance() : data_;
                }
            }

            /**
             * <code>.google.protobuf.Any data = 4;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
            getDataFieldBuilder() {
                if (dataBuilder_ == null) {
                    dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                            getData(),
                            getParentForChildren(),
                            isClean());
                    data_ = null;
                }
                return dataBuilder_;
            }

            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:cn.cy.io.vo.BaseInfo)
        }

        // @@protoc_insertion_point(class_scope:cn.cy.io.vo.BaseInfo)
        private static final BaseInfo DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new BaseInfo();
        }

        public static BaseInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<BaseInfo>
                PARSER = new com.google.protobuf.AbstractParser<BaseInfo>() {
            @Override
            public BaseInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new BaseInfo(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<BaseInfo> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<BaseInfo> getParserForType() {
            return PARSER;
        }

        @Override
        public BaseInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_cn_cy_io_vo_BaseInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_cn_cy_io_vo_BaseInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016BaseInfo.proto\022\013cn.cy.io.vo\032\031google/pr" +
                        "otobuf/any.proto\"]\n\010BaseInfo\022\014\n\004type\030\001 \001" +
                        "(\005\022\014\n\004desc\030\002 \001(\t\022\021\n\trequestId\030\003 \001(\t\022\"\n\004d" +
                        "ata\030\004 \001(\0132\024.google.protobuf.Anyb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                com.google.protobuf.AnyProto.getDescriptor(),
                        }, assigner);
        internal_static_cn_cy_io_vo_BaseInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_cn_cy_io_vo_BaseInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_cn_cy_io_vo_BaseInfo_descriptor,
                new String[]{"Type", "Desc", "RequestId", "Data",});
        com.google.protobuf.AnyProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
